# Generated by Django 4.2.7 on 2023-11-13 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='desc',
        ),
    ]
